spring:
    application:
        name: Book-Rental
    data:
        mongodb:
            database: BookRental
            host: localhost
            port: 27017
            auto-index-creation: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Josephomololu98$
        url: jdbc:mysql://localhost:3306/BookRental
        username: root
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: update
        show-sql: true
    cache:
        type: redis
        cache-names:
            - cache1
            - cache2
        redis:
            time-to-live: 60000
            cache-null-values: false

    redis:
        host: localhost
        port: 6379